config/routes.rb
Rails.application.routes.draw do
  
  resources :quotes do 
    member do 
      put "upvote", to: 'quotes#upvote'
      put 'downvote', to: 'quotes#downvote'
    end
  end
  root 'quotes#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :quote, presence: true, length: {minimum: 3}
  validates :author, presence: true, length: {minimum: 3}
  
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
    User.first
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.all
  end

  def new
    @quote = Quote.new
  end
  
  def create
    @quote = Quote.create(quote_params)
    if @quote.save
      flash[:success] = "Quote Saved"
      redirect_to @quote
    else
      flash[:error] = "There was an error"
      render :new
    end
  end

  def show
    @quote = Quote.find(params[:id])
  end
  
  def upvote
    @quote = Quote.find(params[:id])
    @quote.upvote_by current_user
    redirect_to :back
  end
  
  def downvote
    @quote = Quote.find(params[:id])
    @quote.downvote_by current_user
    redirect_to :back
  end
  
  private
    def quote_params
      params.require(:quote).permit(:quote, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quotes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= link_to "Home", root_path %>
<%= link_to "New Quote", new_quote_path %>
  
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<%= yield %>

</body>
</html>

app/views/quotes/index.html.erb
<h3>Quotes</h3>

<% @quotes.each do |quote| %>
  <%= quote.quote %><br>
  <%= quote.author %>
  <%= link_to "Read More", quote_path(quote) %>
  <br>
  <%= link_to upvote_quote_path(quote), method: :put do %>
    Upvote
    <%= quote.get_upvotes.size %>
  <% end %>
  
  <%= link_to downvote_quote_path(quote), method: :put do %>
    Downvote
    <%= quote.get_downvotes.size %>
  <% end %>
  <br>
  <hr>
<% end %>

app/views/quotes/new.html.erb
<h3>New Quote</h3>
<%= form_for @quote do |f| %>
  <%= f.text_area :quote, :placeholder => "Quote..." %>
  <%= f.text_field :author, :placeholder => "Author" %>
  <%= f.submit "Submit" %>
<% end %>

app/views/quotes/show.html.erb
<h3>Show</h3>

<%= @quote.quote %>
<%= @quote.author %>